# Generated by Django 4.0.6 on 2022-10-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_productos_created_productos_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
