# Generated by Django 4.0.6 on 2022-11-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_productos_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprod',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
    ]
