# Generated by Django 4.0.6 on 2022-10-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sevicios',
            new_name='servicio',
        ),
    ]
